version: '3.8'
services:
  postgres:
    container_name: postgresdb
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: genealogydb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/
    networks:
      - common
    expose:
      - 5432

  backend:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 4000:4000
    networks:
      - common
    environment:
      DATABASE_URL: "postgresql://postgres:12345678@postgres:5432/genealogydb?schema=public"
      JWT_SECRET_KEY: "vya8ygda87dy987y19e812e9ug2197td183tg12gvc712"
      EXPIRES_ACCESS_TOKEN: '1h'
      EXPIRES_REFRESH_TOKEN: '30d'
      PORT: 4000
    expose:
      - 4000
    depends_on:
      - postgres

volumes:
  db-data:

networks:
  common:
    name: genealogy_network